var buttonColours = ["red", "blue", "green", "yellow"];
// for storing the random color generated by the cpu
var gamePattern = [];
// for storing the color clicked by the user
var userClickedPattern = [];
// for storing the level
var level = 0;
// for knowing that the game is started or not
var start = false;


// checking the any button press form the keyboard
$(document).keypress(function () {
    if (start === false) {
        setTimeout(function(){
            nextSequence();
        },1000);
       
        start = true;
    }

});



// When we click then this thing called
$(".btn").click(function () {
    var userChosenColour = $(this).attr("id");
    userClickedPattern.push(userChosenColour);
    playSound(userChosenColour);
    animatePress(userChosenColour);
    checkAnswer(userClickedPattern.length - 1);
});



// function for creating the random number
function nextSequence() {
    // Now we empty the click pattern so that again we start the checking
    userClickedPattern = [];
    level += 1;
    $("#level-title").text("Level " + level);
    var randomNumber = Math.floor(Math.random() * 4);
    var randomChosenColour = buttonColours[randomNumber];
    gamePattern.push(randomChosenColour);
    $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
    playSound(randomChosenColour);


}

// function for playing the sound
function playSound(name) {
    var selectedSong = "sounds/" + name + ".mp3";
    var aud = new Audio(selectedSong);
    aud.play();
}


// function for doing the animation 
function animatePress(currentColour) {
    var userChosenButton = "#" + currentColour;
    $(userChosenButton).addClass("pressed");
    setTimeout(function () {
        $(userChosenButton).removeClass("pressed");
    }, 100);
}


// Function for checking the answer
function checkAnswer(currentLevel) {
    if (userClickedPattern[currentLevel] === gamePattern[currentLevel]) {
        
        if (userClickedPattern.length === gamePattern.length) {
            setTimeout(function () {
                nextSequence();
            }, 1000);
        }
    }
    else {
        
        var audio = new Audio("sounds/wrong.mp3");
        audio.play();
        $("body").addClass("game-over");
        setTimeout(function () {
            $("body").removeClass("game-over");
        }, 200);
        $("#level-title").text("Game Over, You pass " + level + " level.  Press Any Key to Restart");
        startOver();
        
       
    }
}


// Function for again start if the game is over
function startOver(){
   level = 0;
   start = false;
   gamePattern = [];
}




